#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common

runcmd:
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab